# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Chat' do
pod 'IQKeyboardManagerSwift'
pod 'Alamofire'
pod 'AlamofireNetworkActivityIndicator'
pod 'AlamofireImage'
pod 'KOActivityIndicator'
pod 'ENSwiftSideMenu'
end

target 'ChatTests' do

end

target 'ChatUITests' do

end

